[tool.poetry]
name = "korone"
version = "1.1.0"
description = "An interactive and multi-function Telegram bot, made especially for Telegram groups."
authors = ["Hitalo <contact@amanoteam.com>"]
license = "GPLv3+"
readme = "README.md"
repository = "https://github.com/AmanoTeam/PyKorone"
documentation = "https://github.com/AmanoTeam/PyKorone/blob/main/README.md"

keywords = ["chat", "telegram", "bot", "telegram-bot", "pyrogram", "black", "flake8"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: AsyncIO",
    "Natural Language :: Portuguese (Brazilian)",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Topic :: Internet",
    "Topic :: Communications",
    "Topic :: Communications :: Chat"
]

exclude = ["korone/config.py", "korone/client.session", "korone/client.session-journal", "korone/database/*.sqlite"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/AmanoTeam/PyKorone/issues"
"Community" = "https://t.me/SpamTherapy"

[tool.poetry.dependencies]
python = "^3.7"
pyrogram = "1.2.6"
tgcrypto = "1.2.2"
pyromod = "1.5"
rich = "10.0.0"
tortoise-orm = "0.17.1"
Pillow = "8.1.2"
httpx = {version = "0.17.1", extras = ["http2"]}
python-rapidjson = "1.0"
kantex = "0.2.0"
spamwatch = "0.3.0"
search-engine-parser = "0.6.2"
meval = "2.5"
cowpy = "1.1.0"
jikanpy = "4.3.1"
asyncpraw = "7.2.0"
pynewton = "^1.1.0"
youtube_dl = "2021.3.31"
wheel = "^0.36.2"
gpytranslate = "0.3.1"
wikipedia = "1.4.0"
python-anilist = {git = "https://github.com/AmanoTeam/python-anilist", rev = "main"}
SpeechRecognition = "3.8.1"
pydub = "0.24.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
